name:                typelevel-playground
version:             0.0.0.0
github:              "laserpants/typelevel-playground"
license:             BSD3
author:              "Heikki Johannes Hildén"
maintainer:          "hildenjohannes@gmail.com"
copyright:           "2021 laserpants"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/typelevel-playground#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell

library:
  source-dirs: src

executables:
  typelevel-playground-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typelevel-playground

tests:
  typelevel-playground-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typelevel-playground
